- 👋 Hi, I’m @mdpionto
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
mdpionto/mdpionto is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
sh/sdcard/chaozhuo.gameasslstant2/lnlect.sh
